services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zctl
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s
      retries: 10

  core:
    build:
      context: .
      dockerfile: apps/core/Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/zctl
      PORT: '3000'
      HOST: '0.0.0.0'
      JWT_SECRET: '${JWT_SECRET:-dev-secret-change-in-production-1}'
    depends_on:
      postgres:
        condition: service_healthy

  agent:
    build:
      context: ./agents/go-agent
      dockerfile: Dockerfile
    environment:
      CORE_URL: http://core:3000
      HOSTNAME: docker-agent
    depends_on:
      core:
        condition: service_started

volumes:
  pgdata:
